services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tezicare-app
    working_dir: /var/www/tezicare-api.tezi.co.ke
    user: "${UID}:${GID}"
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
    depends_on:
      - db
    networks:
      - tezicare

  web:
    image: nginx:alpine
    container_name: tezicare-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tezicare

  db:
    image: mysql:8.0
    container_name: tezicare-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: s)|]wTB,**
      MYSQL_DATABASE: tezicare_db
      MYSQL_USER: tezicare_app
      MYSQL_PASSWORD: s)|]wTB,**
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tezicare

  composer:
    image: composer:latest
    container_name: tezicare-composer
    working_dir: /var/www/tezicare-api.tezi.co.ke
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
    networks:
      - tezicare

volumes:
  dbdata:

networks:
  tezicare:
