services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tezicare-app
    working_dir: /var/www/tezicare-api.tezi.co.ke
    user: "${UID}:${GID}"
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
    depends_on:
      - db
    networks:
      - tezicare
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  web:
    image: nginx:alpine
    container_name: tezicare-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tezicare
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  db:
    image: mysql:8.0
    container_name: tezicare-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: s)|]wTB,**
      MYSQL_DATABASE: tezicare_db
      MYSQL_USER: tezicare_app
      MYSQL_PASSWORD: s)|]wTB,**
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tezicare

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tezicare-phpmyadmin
    restart: always
    ports:
      - "8768:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: s)|]wTB,**
    depends_on:
      - db
    networks:
      - tezicare

  composer:
    image: composer:latest
    container_name: tezicare-composer
    working_dir: /var/www/tezicare-api.tezi.co.ke
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www/tezicare-api.tezi.co.ke
    networks:
      - tezicare

volumes:
  dbdata:

networks:
  tezicare:
